[2025-05-08T03:55:45.143+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-08T03:55:45.154+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-08T03:55:37.730339+00:00 [queued]>
[2025-05-08T03:55:45.159+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-08T03:55:37.730339+00:00 [queued]>
[2025-05-08T03:55:45.159+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-08T03:55:45.168+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): ins_videos_scraper> on 2025-05-08 03:55:37.730339+00:00
[2025-05-08T03:55:45.171+0000] {standard_task_runner.py:72} INFO - Started process 189 to run task
[2025-05-08T03:55:45.174+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'instagram_videos_scraper_dag', 'ins_videos_scraper', 'manual__2025-05-08T03:55:37.730339+00:00', '--job-id', '4930', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpfs8skhnn']
[2025-05-08T03:55:45.176+0000] {standard_task_runner.py:105} INFO - Job 4930: Subtask ins_videos_scraper
[2025-05-08T03:55:45.210+0000] {task_command.py:467} INFO - Running <TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-08T03:55:37.730339+00:00 [running]> on host 2c71b1bd6896
[2025-05-08T03:55:45.275+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='instagram_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='ins_videos_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T03:55:37.730339+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T03:55:37.730339+00:00'
[2025-05-08T03:55:45.276+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-08T03:56:09.482+0000] {selenium_manager.py:133} WARNING - The chromedriver version (136.0.7103.59) detected in PATH at /usr/bin/chromedriver might not be compatible with the detected chrome version (136.0.7103.92); currently, chromedriver 136.0.7103.92 is recommended for chrome 136.*, so it is advised to delete the driver in PATH and retry
[2025-05-08T04:00:43.213+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/tasks/insta_scraper.py", line 17, in ins_videos_scraper
    scraper = ProfileScraper(id)
  File "/opt/airflow/dags/utils/instagram_profile.py", line 16, in __init__
    super().__init__(
  File "/opt/airflow/dags/utils/instagram_base.py", line 26, in __init__
    self._driver.get(self._base_url)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x55d95ae1da8e <unknown>
#1 0x55d95a8dab0b <unknown>
#2 0x55d95a8c6306 <unknown>
#3 0x55d95a8c60bc <unknown>
#4 0x55d95a8c4608 <unknown>
#5 0x55d95a8c4ab9 <unknown>
#6 0x55d95a8d2160 <unknown>
#7 0x55d95a8e84ff <unknown>
#8 0x55d95a8eda4b <unknown>
#9 0x55d95a8c502d <unknown>
#10 0x55d95a8e82f7 <unknown>
#11 0x55d95a96fcf7 <unknown>
#12 0x55d95a94e9b3 <unknown>
#13 0x55d95a918c59 <unknown>
#14 0x55d95a919a08 <unknown>
#15 0x55d95adea40a <unknown>
#16 0x55d95aded85e <unknown>
#17 0x55d95aded308 <unknown>
#18 0x55d95adedce5 <unknown>
#19 0x55d95add3b7b <unknown>
#20 0x55d95adee050 <unknown>
#21 0x55d95adbcae9 <unknown>
#22 0x55d95ae0cdf5 <unknown>
#23 0x55d95ae0cfdb <unknown>
#24 0x55d95ae1cc05 <unknown>
#25 0x7fc3d914a134 <unknown>

[2025-05-08T04:00:43.228+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=instagram_videos_scraper_dag, task_id=ins_videos_scraper, run_id=manual__2025-05-08T03:55:37.730339+00:00, execution_date=20250508T035537, start_date=20250508T035545, end_date=20250508T040043
[2025-05-08T04:00:43.246+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-08T04:00:43.246+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4930 for task ins_videos_scraper (Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x55d95ae1da8e <unknown>
#1 0x55d95a8dab0b <unknown>
#2 0x55d95a8c6306 <unknown>
#3 0x55d95a8c60bc <unknown>
#4 0x55d95a8c4608 <unknown>
#5 0x55d95a8c4ab9 <unknown>
#6 0x55d95a8d2160 <unknown>
#7 0x55d95a8e84ff <unknown>
#8 0x55d95a8eda4b <unknown>
#9 0x55d95a8c502d <unknown>
#10 0x55d95a8e82f7 <unknown>
#11 0x55d95a96fcf7 <unknown>
#12 0x55d95a94e9b3 <unknown>
#13 0x55d95a918c59 <unknown>
#14 0x55d95a919a08 <unknown>
#15 0x55d95adea40a <unknown>
#16 0x55d95aded85e <unknown>
#17 0x55d95aded308 <unknown>
#18 0x55d95adedce5 <unknown>
#19 0x55d95add3b7b <unknown>
#20 0x55d95adee050 <unknown>
#21 0x55d95adbcae9 <unknown>
#22 0x55d95ae0cdf5 <unknown>
#23 0x55d95ae0cfdb <unknown>
#24 0x55d95ae1cc05 <unknown>
#25 0x7fc3d914a134 <unknown>
; 189)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/tasks/insta_scraper.py", line 17, in ins_videos_scraper
    scraper = ProfileScraper(id)
  File "/opt/airflow/dags/utils/instagram_profile.py", line 16, in __init__
    super().__init__(
  File "/opt/airflow/dags/utils/instagram_base.py", line 26, in __init__
    self._driver.get(self._base_url)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x55d95ae1da8e <unknown>
#1 0x55d95a8dab0b <unknown>
#2 0x55d95a8c6306 <unknown>
#3 0x55d95a8c60bc <unknown>
#4 0x55d95a8c4608 <unknown>
#5 0x55d95a8c4ab9 <unknown>
#6 0x55d95a8d2160 <unknown>
#7 0x55d95a8e84ff <unknown>
#8 0x55d95a8eda4b <unknown>
#9 0x55d95a8c502d <unknown>
#10 0x55d95a8e82f7 <unknown>
#11 0x55d95a96fcf7 <unknown>
#12 0x55d95a94e9b3 <unknown>
#13 0x55d95a918c59 <unknown>
#14 0x55d95a919a08 <unknown>
#15 0x55d95adea40a <unknown>
#16 0x55d95aded85e <unknown>
#17 0x55d95aded308 <unknown>
#18 0x55d95adedce5 <unknown>
#19 0x55d95add3b7b <unknown>
#20 0x55d95adee050 <unknown>
#21 0x55d95adbcae9 <unknown>
#22 0x55d95ae0cdf5 <unknown>
#23 0x55d95ae0cfdb <unknown>
#24 0x55d95ae1cc05 <unknown>
#25 0x7fc3d914a134 <unknown>

[2025-05-08T04:00:43.265+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-05-08T04:00:43.279+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-08T04:00:43.281+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
