[2025-05-13T02:20:32.857+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-13T02:20:32.868+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-13T02:20:31.909893+00:00 [queued]>
[2025-05-13T02:20:32.873+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-13T02:20:31.909893+00:00 [queued]>
[2025-05-13T02:20:32.873+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-13T02:20:32.881+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): ins_videos_scraper> on 2025-05-13 02:20:31.909893+00:00
[2025-05-13T02:20:32.883+0000] {standard_task_runner.py:72} INFO - Started process 449 to run task
[2025-05-13T02:20:32.886+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'instagram_videos_scraper_dag', 'ins_videos_scraper', 'manual__2025-05-13T02:20:31.909893+00:00', '--job-id', '5324', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpqjo60y5_']
[2025-05-13T02:20:32.887+0000] {standard_task_runner.py:105} INFO - Job 5324: Subtask ins_videos_scraper
[2025-05-13T02:20:32.920+0000] {task_command.py:467} INFO - Running <TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-13T02:20:31.909893+00:00 [running]> on host 79b7354865cb
[2025-05-13T02:20:32.970+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='instagram_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='ins_videos_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T02:20:31.909893+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-13T02:20:31.909893+00:00'
[2025-05-13T02:20:32.971+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-13T02:20:32.972+0000] {logging_mixin.py:190} INFO - Scraping Instagram profile: baukrysie
[2025-05-13T02:20:33.006+0000] {selenium_manager.py:133} WARNING - The chromedriver version (136.0.7103.59) detected in PATH at /usr/bin/chromedriver might not be compatible with the detected chrome version (136.0.7103.92); currently, chromedriver 136.0.7103.92 is recommended for chrome 136.*, so it is advised to delete the driver in PATH and retry
[2025-05-13T02:20:33.822+0000] {logging_mixin.py:190} INFO - url: https://www.instagram.com/baukrysie/
[2025-05-13T02:20:35.571+0000] {logging_mixin.py:190} INFO - Step 1 of 2 - Loading profile page
[2025-05-13T02:20:35.571+0000] {logging_mixin.py:190} INFO - Extracting videos...
[2025-05-13T02:20:38.605+0000] {logging_mixin.py:190} INFO - Count: 1, Limit: 10
[2025-05-13T02:20:38.605+0000] {logging_mixin.py:190} INFO - Scrolling... 1 iterations
[2025-05-13T02:20:38.800+0000] {logging_mixin.py:190} INFO - Found 51 video tags
[2025-05-13T02:20:38.963+0000] {logging_mixin.py:190} INFO - Extracted 0 video URLs
[2025-05-13T02:20:38.964+0000] {logging_mixin.py:190} INFO -  No data found
[2025-05-13T02:20:39.094+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe5efdb220>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b3add685649356e4d27e5dc8b2505708
[2025-05-13T02:20:39.095+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe5efdb3a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b3add685649356e4d27e5dc8b2505708
[2025-05-13T02:20:39.095+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe5efdbd30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/b3add685649356e4d27e5dc8b2505708
[2025-05-13T02:20:39.096+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-13T02:20:39.103+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-13T02:20:39.104+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=instagram_videos_scraper_dag, task_id=ins_videos_scraper, run_id=manual__2025-05-13T02:20:31.909893+00:00, execution_date=20250513T022031, start_date=20250513T022032, end_date=20250513T022039
[2025-05-13T02:20:39.116+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-05-13T02:20:39.131+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-13T02:20:39.133+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
