[2025-05-09T09:17:58.025+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-09T09:17:58.037+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper manual__2025-05-09T09:17:56.809289+00:00 [queued]>
[2025-05-09T09:17:58.041+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper manual__2025-05-09T09:17:56.809289+00:00 [queued]>
[2025-05-09T09:17:58.042+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-09T09:17:58.052+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): tiktok_videos_scraper> on 2025-05-09 09:17:56.809289+00:00
[2025-05-09T09:17:58.055+0000] {standard_task_runner.py:72} INFO - Started process 131 to run task
[2025-05-09T09:17:58.058+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'tiktok_videos_scraper_dag', 'tiktok_videos_scraper', 'manual__2025-05-09T09:17:56.809289+00:00', '--job-id', '5180', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpbwph9sfg']
[2025-05-09T09:17:58.060+0000] {standard_task_runner.py:105} INFO - Job 5180: Subtask tiktok_videos_scraper
[2025-05-09T09:17:58.095+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper manual__2025-05-09T09:17:56.809289+00:00 [running]> on host 14fa56807961
[2025-05-09T09:17:58.160+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='tiktok_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='tiktok_videos_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-05-09T09:17:56.809289+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-09T09:17:56.809289+00:00'
[2025-05-09T09:17:58.161+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-09T09:47:50.549+0000] {local_task_job_runner.py:341} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-09T09:47:50.561+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2025-05-09T09:47:50.563+0000] {process_utils.py:132} INFO - Sending 15 to group 131. PIDs of all processes in the group: [134, 146, 153, 154, 182, 183, 237, 238, 271, 319, 131]
[2025-05-09T09:47:50.563+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 131
[2025-05-09T09:47:50.567+0000] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-09T09:47:50.658+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=237, status='terminated', started='09:18:00') (237) terminated with exit code None
[2025-05-09T09:47:50.659+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=238, status='terminated', started='09:18:00') (238) terminated with exit code None
[2025-05-09T09:47:50.659+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=271, status='terminated', started='09:18:00') (271) terminated with exit code None
[2025-05-09T09:47:50.687+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=153, status='terminated', started='09:17:59') (153) terminated with exit code None
[2025-05-09T09:47:50.687+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=154, status='terminated', started='09:17:59') (154) terminated with exit code None
[2025-05-09T09:47:50.781+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=182, status='terminated', started='09:17:59') (182) terminated with exit code None
[2025-05-09T09:47:50.877+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=183, status='terminated', started='09:17:59') (183) terminated with exit code None
[2025-05-09T09:47:50.878+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=319, status='terminated', started='09:20:59') (319) terminated with exit code None
[2025-05-09T09:47:50.878+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=146, status='terminated', started='09:17:58') (146) terminated with exit code None
[2025-05-09T09:48:45.606+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=134, name='node', status='sleeping', started='09:17:58') did not respond to SIGTERM. Trying SIGKILL
[2025-05-09T09:48:45.609+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=131, name='airflow task ru', status='sleeping', started='09:17:57') did not respond to SIGTERM. Trying SIGKILL
[2025-05-09T09:48:45.611+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 131
[2025-05-09T09:48:45.626+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=134, name='node', status='terminated', started='09:17:58') (134) terminated with exit code None
[2025-05-09T09:48:45.626+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=131, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='09:17:57') (131) terminated with exit code -9
[2025-05-09T09:48:45.627+0000] {standard_task_runner.py:190} ERROR - ('Job 5180 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
