[2025-05-08T04:30:17.265+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-08T04:30:17.279+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-08T04:30:10.392622+00:00 [queued]>
[2025-05-08T04:30:17.285+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-08T04:30:10.392622+00:00 [queued]>
[2025-05-08T04:30:17.286+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-08T04:30:17.295+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): ins_videos_scraper> on 2025-05-08 04:30:10.392622+00:00
[2025-05-08T04:30:17.298+0000] {standard_task_runner.py:72} INFO - Started process 668 to run task
[2025-05-08T04:30:17.301+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'instagram_videos_scraper_dag', 'ins_videos_scraper', 'manual__2025-05-08T04:30:10.392622+00:00', '--job-id', '4941', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp5qzs7g7o']
[2025-05-08T04:30:17.302+0000] {standard_task_runner.py:105} INFO - Job 4941: Subtask ins_videos_scraper
[2025-05-08T04:30:17.342+0000] {task_command.py:467} INFO - Running <TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-08T04:30:10.392622+00:00 [running]> on host b933188c6fc6
[2025-05-08T04:30:17.414+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='instagram_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='ins_videos_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T04:30:10.392622+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T04:30:10.392622+00:00'
[2025-05-08T04:30:17.415+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-08T04:30:17.448+0000] {selenium_manager.py:133} WARNING - The chromedriver version (136.0.7103.59) detected in PATH at /usr/bin/chromedriver might not be compatible with the detected chrome version (136.0.7103.92); currently, chromedriver 136.0.7103.92 is recommended for chrome 136.*, so it is advised to delete the driver in PATH and retry
[2025-05-08T04:30:18.230+0000] {logging_mixin.py:190} INFO - url: https://www.instagram.com/baukrysie/
[2025-05-08T04:31:35.029+0000] {job.py:229} INFO - Heartbeat recovered after 12.74 seconds
[2025-05-08T04:31:58.176+0000] {job.py:229} INFO - Heartbeat recovered after 13.07 seconds
[2025-05-08T04:32:19.983+0000] {job.py:229} INFO - Heartbeat recovered after 12.73 seconds
[2025-05-08T04:34:51.214+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/tasks/insta_scraper.py", line 17, in ins_videos_scraper
    scraper = ProfileScraper(id)
  File "/opt/airflow/dags/utils/instagram_profile.py", line 16, in __init__
    super().__init__(user_id, base_url=f"https://www.instagram.com/{user_id}/")
  File "/opt/airflow/dags/utils/instagram_base.py", line 27, in __init__
    self._driver.get(self._base_url)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x559879e6da8e <unknown>
#1 0x55987992ab0b <unknown>
#2 0x559879916306 <unknown>
#3 0x5598799160bc <unknown>
#4 0x559879914608 <unknown>
#5 0x559879914ab9 <unknown>
#6 0x559879922160 <unknown>
#7 0x5598799384ff <unknown>
#8 0x55987993da4b <unknown>
#9 0x55987991502d <unknown>
#10 0x5598799382f7 <unknown>
#11 0x5598799bfcf7 <unknown>
#12 0x55987999e9b3 <unknown>
#13 0x559879968c59 <unknown>
#14 0x559879969a08 <unknown>
#15 0x559879e3a40a <unknown>
#16 0x559879e3d85e <unknown>
#17 0x559879e3d308 <unknown>
#18 0x559879e3dce5 <unknown>
#19 0x559879e23b7b <unknown>
#20 0x559879e3e050 <unknown>
#21 0x559879e0cae9 <unknown>
#22 0x559879e5cdf5 <unknown>
#23 0x559879e5cfdb <unknown>
#24 0x559879e6cc05 <unknown>
#25 0x7fcaa7083134 <unknown>

[2025-05-08T04:34:51.231+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=instagram_videos_scraper_dag, task_id=ins_videos_scraper, run_id=manual__2025-05-08T04:30:10.392622+00:00, execution_date=20250508T043010, start_date=20250508T043017, end_date=20250508T043451
[2025-05-08T04:34:51.244+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-08T04:34:51.245+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4941 for task ins_videos_scraper (Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x559879e6da8e <unknown>
#1 0x55987992ab0b <unknown>
#2 0x559879916306 <unknown>
#3 0x5598799160bc <unknown>
#4 0x559879914608 <unknown>
#5 0x559879914ab9 <unknown>
#6 0x559879922160 <unknown>
#7 0x5598799384ff <unknown>
#8 0x55987993da4b <unknown>
#9 0x55987991502d <unknown>
#10 0x5598799382f7 <unknown>
#11 0x5598799bfcf7 <unknown>
#12 0x55987999e9b3 <unknown>
#13 0x559879968c59 <unknown>
#14 0x559879969a08 <unknown>
#15 0x559879e3a40a <unknown>
#16 0x559879e3d85e <unknown>
#17 0x559879e3d308 <unknown>
#18 0x559879e3dce5 <unknown>
#19 0x559879e23b7b <unknown>
#20 0x559879e3e050 <unknown>
#21 0x559879e0cae9 <unknown>
#22 0x559879e5cdf5 <unknown>
#23 0x559879e5cfdb <unknown>
#24 0x559879e6cc05 <unknown>
#25 0x7fcaa7083134 <unknown>
; 668)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/tasks/insta_scraper.py", line 17, in ins_videos_scraper
    scraper = ProfileScraper(id)
  File "/opt/airflow/dags/utils/instagram_profile.py", line 16, in __init__
    super().__init__(user_id, base_url=f"https://www.instagram.com/{user_id}/")
  File "/opt/airflow/dags/utils/instagram_base.py", line 27, in __init__
    self._driver.get(self._base_url)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x559879e6da8e <unknown>
#1 0x55987992ab0b <unknown>
#2 0x559879916306 <unknown>
#3 0x5598799160bc <unknown>
#4 0x559879914608 <unknown>
#5 0x559879914ab9 <unknown>
#6 0x559879922160 <unknown>
#7 0x5598799384ff <unknown>
#8 0x55987993da4b <unknown>
#9 0x55987991502d <unknown>
#10 0x5598799382f7 <unknown>
#11 0x5598799bfcf7 <unknown>
#12 0x55987999e9b3 <unknown>
#13 0x559879968c59 <unknown>
#14 0x559879969a08 <unknown>
#15 0x559879e3a40a <unknown>
#16 0x559879e3d85e <unknown>
#17 0x559879e3d308 <unknown>
#18 0x559879e3dce5 <unknown>
#19 0x559879e23b7b <unknown>
#20 0x559879e3e050 <unknown>
#21 0x559879e0cae9 <unknown>
#22 0x559879e5cdf5 <unknown>
#23 0x559879e5cfdb <unknown>
#24 0x559879e6cc05 <unknown>
#25 0x7fcaa7083134 <unknown>

[2025-05-08T04:34:51.292+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-05-08T04:34:51.306+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-08T04:34:51.308+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
