[2025-05-15T09:49:55.413+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-15T09:49:55.428+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper_task manual__2025-05-15T09:49:54.278409+00:00 [queued]>
[2025-05-15T09:49:55.434+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper_task manual__2025-05-15T09:49:54.278409+00:00 [queued]>
[2025-05-15T09:49:55.434+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-15T09:49:55.442+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): tiktok_videos_scraper_task> on 2025-05-15 09:49:54.278409+00:00
[2025-05-15T09:49:55.445+0000] {standard_task_runner.py:72} INFO - Started process 329 to run task
[2025-05-15T09:49:55.448+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'tiktok_videos_scraper_dag', 'tiktok_videos_scraper_task', 'manual__2025-05-15T09:49:54.278409+00:00', '--job-id', '5972', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_tiktok.py', '--cfg-path', '/tmp/tmpq6lr4n4c']
[2025-05-15T09:49:55.450+0000] {standard_task_runner.py:105} INFO - Job 5972: Subtask tiktok_videos_scraper_task
[2025-05-15T09:49:55.484+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper_task manual__2025-05-15T09:49:54.278409+00:00 [running]> on host 8579eb2523da
[2025-05-15T09:49:55.546+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='tiktok_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='tiktok_videos_scraper_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T09:49:54.278409+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-15T09:49:54.278409+00:00'
[2025-05-15T09:49:55.547+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-15T09:53:22.202+0000] {local_task_job_runner.py:341} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-15T09:53:22.203+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2025-05-15T09:53:22.204+0000] {process_utils.py:132} INFO - Sending 15 to group 329. PIDs of all processes in the group: [332, 344, 351, 352, 380, 389, 435, 436, 460, 513, 329]
[2025-05-15T09:53:22.205+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 329
[2025-05-15T09:53:22.205+0000] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-15T09:53:22.212+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=435, status='terminated', started='09:49:57') (435) terminated with exit code None
[2025-05-15T09:53:22.212+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=436, status='terminated', started='09:49:57') (436) terminated with exit code None
[2025-05-15T09:53:22.265+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=351, status='terminated', started='09:49:56') (351) terminated with exit code None
[2025-05-15T09:53:22.265+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=352, status='terminated', started='09:49:56') (352) terminated with exit code None
[2025-05-15T09:53:22.358+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=344, status='terminated', started='09:49:56') (344) terminated with exit code None
[2025-05-15T09:53:22.450+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=513, status='terminated', started='09:52:57') (513) terminated with exit code None
[2025-05-15T09:53:22.451+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=389, status='terminated', started='09:49:57') (389) terminated with exit code None
[2025-05-15T09:53:22.451+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=460, status='terminated', started='09:49:57') (460) terminated with exit code None
[2025-05-15T09:53:22.451+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=380, status='terminated', started='09:49:57') (380) terminated with exit code None
[2025-05-15T09:54:22.242+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=332, name='node', status='sleeping', started='09:49:55') did not respond to SIGTERM. Trying SIGKILL
[2025-05-15T09:54:22.246+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=329, name='airflow task ru', status='sleeping', started='09:49:55') did not respond to SIGTERM. Trying SIGKILL
[2025-05-15T09:54:22.246+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 329
[2025-05-15T09:54:22.253+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=329, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='09:49:55') (329) terminated with exit code -9
[2025-05-15T09:54:22.254+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=332, name='node', status='terminated', started='09:49:55') (332) terminated with exit code None
[2025-05-15T09:54:22.254+0000] {standard_task_runner.py:190} ERROR - ('Job 5972 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
