[2025-05-12T04:07:00.748+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-12T04:07:00.762+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper manual__2025-05-12T04:06:59.417431+00:00 [queued]>
[2025-05-12T04:07:00.768+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper manual__2025-05-12T04:06:59.417431+00:00 [queued]>
[2025-05-12T04:07:00.768+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-12T04:07:00.777+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): tiktok_videos_scraper> on 2025-05-12 04:06:59.417431+00:00
[2025-05-12T04:07:00.780+0000] {standard_task_runner.py:72} INFO - Started process 2569 to run task
[2025-05-12T04:07:00.783+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'tiktok_videos_scraper_dag', 'tiktok_videos_scraper', 'manual__2025-05-12T04:06:59.417431+00:00', '--job-id', '5199', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpqqmmzcor']
[2025-05-12T04:07:00.785+0000] {standard_task_runner.py:105} INFO - Job 5199: Subtask tiktok_videos_scraper
[2025-05-12T04:07:00.821+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper manual__2025-05-12T04:06:59.417431+00:00 [running]> on host 14fa56807961
[2025-05-12T04:07:00.885+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='tiktok_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='tiktok_videos_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T04:06:59.417431+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-12T04:06:59.417431+00:00'
[2025-05-12T04:07:00.886+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-12T04:18:15.830+0000] {local_task_job_runner.py:341} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-12T04:18:15.832+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2025-05-12T04:18:15.833+0000] {process_utils.py:132} INFO - Sending 15 to group 2569. PIDs of all processes in the group: [2572, 2584, 2591, 2592, 2615, 2629, 2669, 2671, 2697, 2749, 2569]
[2025-05-12T04:18:15.833+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2569
[2025-05-12T04:18:15.834+0000] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-12T04:18:15.929+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2592, status='terminated', started='04:07:01') (2592) terminated with exit code None
[2025-05-12T04:18:16.025+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2669, status='terminated', started='04:07:02') (2669) terminated with exit code None
[2025-05-12T04:18:16.026+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2697, status='terminated', started='04:07:02') (2697) terminated with exit code None
[2025-05-12T04:18:16.026+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2671, status='terminated', started='04:07:02') (2671) terminated with exit code None
[2025-05-12T04:18:16.026+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2629, status='terminated', started='04:07:02') (2629) terminated with exit code None
[2025-05-12T04:18:16.026+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2749, status='terminated', started='04:10:02') (2749) terminated with exit code None
[2025-05-12T04:18:16.026+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2615, status='terminated', started='04:07:02') (2615) terminated with exit code None
[2025-05-12T04:18:16.123+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2584, status='terminated', started='04:07:01') (2584) terminated with exit code None
[2025-05-12T04:18:16.124+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2591, status='terminated', started='04:07:01') (2591) terminated with exit code None
[2025-05-12T04:19:10.856+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=2572, name='node', status='sleeping', started='04:07:01') did not respond to SIGTERM. Trying SIGKILL
[2025-05-12T04:19:10.857+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=2569, name='airflow task ru', status='sleeping', started='04:07:00') did not respond to SIGTERM. Trying SIGKILL
[2025-05-12T04:19:10.858+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 2569
[2025-05-12T04:19:10.866+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2572, name='node', status='terminated', started='04:07:01') (2572) terminated with exit code None
[2025-05-12T04:19:10.866+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2569, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='04:07:00') (2569) terminated with exit code -9
[2025-05-12T04:19:10.867+0000] {standard_task_runner.py:190} ERROR - ('Job 5199 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
