[2025-05-08T07:10:50.476+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-08T07:10:50.486+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-08T07:10:49.234781+00:00 [queued]>
[2025-05-08T07:10:50.491+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-08T07:10:49.234781+00:00 [queued]>
[2025-05-08T07:10:50.491+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-08T07:10:50.499+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): ins_videos_scraper> on 2025-05-08 07:10:49.234781+00:00
[2025-05-08T07:10:50.501+0000] {standard_task_runner.py:72} INFO - Started process 76 to run task
[2025-05-08T07:10:50.504+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'instagram_videos_scraper_dag', 'ins_videos_scraper', 'manual__2025-05-08T07:10:49.234781+00:00', '--job-id', '5117', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpr85sd68b']
[2025-05-08T07:10:50.505+0000] {standard_task_runner.py:105} INFO - Job 5117: Subtask ins_videos_scraper
[2025-05-08T07:10:50.539+0000] {task_command.py:467} INFO - Running <TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-08T07:10:49.234781+00:00 [running]> on host 2a0ed4e74a0c
[2025-05-08T07:10:50.591+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='instagram_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='ins_videos_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-05-08T07:10:49.234781+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-08T07:10:49.234781+00:00'
[2025-05-08T07:10:50.592+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-08T07:10:50.594+0000] {logging_mixin.py:190} INFO - Scraping Instagram profile: baukrysie
[2025-05-08T07:10:50.620+0000] {selenium_manager.py:133} WARNING - The chromedriver version (136.0.7103.59) detected in PATH at /usr/bin/chromedriver might not be compatible with the detected chrome version (136.0.7103.92); currently, chromedriver 136.0.7103.92 is recommended for chrome 136.*, so it is advised to delete the driver in PATH and retry
[2025-05-08T07:10:51.449+0000] {logging_mixin.py:190} INFO - url: https://www.instagram.com/baukrysie/
[2025-05-08T07:15:23.903+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/tasks/insta_scraper.py", line 17, in ins_videos_scraper
    scraper = ProfileScraper(id)
  File "/opt/airflow/dags/utils/instagram_profile.py", line 17, in __init__
    super().__init__(user_id, base_url=f"https://www.instagram.com/{user_id}/")
  File "/opt/airflow/dags/utils/instagram_base.py", line 34, in __init__
    self._driver.get(self._base_url)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x5649976b9a8e <unknown>
#1 0x564997176b0b <unknown>
#2 0x564997162306 <unknown>
#3 0x5649971620bc <unknown>
#4 0x564997160608 <unknown>
#5 0x564997160ab9 <unknown>
#6 0x56499716e160 <unknown>
#7 0x5649971844ff <unknown>
#8 0x564997189a4b <unknown>
#9 0x56499716102d <unknown>
#10 0x5649971842f7 <unknown>
#11 0x56499720bcf7 <unknown>
#12 0x5649971ea9b3 <unknown>
#13 0x5649971b4c59 <unknown>
#14 0x5649971b5a08 <unknown>
#15 0x56499768640a <unknown>
#16 0x56499768985e <unknown>
#17 0x564997689308 <unknown>
#18 0x564997689ce5 <unknown>
#19 0x56499766fb7b <unknown>
#20 0x56499768a050 <unknown>
#21 0x564997658ae9 <unknown>
#22 0x5649976a8df5 <unknown>
#23 0x5649976a8fdb <unknown>
#24 0x5649976b8c05 <unknown>
#25 0x7feab7d65134 <unknown>

[2025-05-08T07:15:23.925+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=instagram_videos_scraper_dag, task_id=ins_videos_scraper, run_id=manual__2025-05-08T07:10:49.234781+00:00, execution_date=20250508T071049, start_date=20250508T071050, end_date=20250508T071523
[2025-05-08T07:15:23.938+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-08T07:15:23.939+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5117 for task ins_videos_scraper (Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x5649976b9a8e <unknown>
#1 0x564997176b0b <unknown>
#2 0x564997162306 <unknown>
#3 0x5649971620bc <unknown>
#4 0x564997160608 <unknown>
#5 0x564997160ab9 <unknown>
#6 0x56499716e160 <unknown>
#7 0x5649971844ff <unknown>
#8 0x564997189a4b <unknown>
#9 0x56499716102d <unknown>
#10 0x5649971842f7 <unknown>
#11 0x56499720bcf7 <unknown>
#12 0x5649971ea9b3 <unknown>
#13 0x5649971b4c59 <unknown>
#14 0x5649971b5a08 <unknown>
#15 0x56499768640a <unknown>
#16 0x56499768985e <unknown>
#17 0x564997689308 <unknown>
#18 0x564997689ce5 <unknown>
#19 0x56499766fb7b <unknown>
#20 0x56499768a050 <unknown>
#21 0x564997658ae9 <unknown>
#22 0x5649976a8df5 <unknown>
#23 0x5649976a8fdb <unknown>
#24 0x5649976b8c05 <unknown>
#25 0x7feab7d65134 <unknown>
; 76)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/tasks/insta_scraper.py", line 17, in ins_videos_scraper
    scraper = ProfileScraper(id)
  File "/opt/airflow/dags/utils/instagram_profile.py", line 17, in __init__
    super().__init__(user_id, base_url=f"https://www.instagram.com/{user_id}/")
  File "/opt/airflow/dags/utils/instagram_base.py", line 34, in __init__
    self._driver.get(self._base_url)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=136.0.7103.92)
Stacktrace:
#0 0x5649976b9a8e <unknown>
#1 0x564997176b0b <unknown>
#2 0x564997162306 <unknown>
#3 0x5649971620bc <unknown>
#4 0x564997160608 <unknown>
#5 0x564997160ab9 <unknown>
#6 0x56499716e160 <unknown>
#7 0x5649971844ff <unknown>
#8 0x564997189a4b <unknown>
#9 0x56499716102d <unknown>
#10 0x5649971842f7 <unknown>
#11 0x56499720bcf7 <unknown>
#12 0x5649971ea9b3 <unknown>
#13 0x5649971b4c59 <unknown>
#14 0x5649971b5a08 <unknown>
#15 0x56499768640a <unknown>
#16 0x56499768985e <unknown>
#17 0x564997689308 <unknown>
#18 0x564997689ce5 <unknown>
#19 0x56499766fb7b <unknown>
#20 0x56499768a050 <unknown>
#21 0x564997658ae9 <unknown>
#22 0x5649976a8df5 <unknown>
#23 0x5649976a8fdb <unknown>
#24 0x5649976b8c05 <unknown>
#25 0x7feab7d65134 <unknown>

[2025-05-08T07:15:23.946+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-05-08T07:15:23.957+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-08T07:15:23.959+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
