[2025-05-23T09:37:42.398+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-23T09:37:42.424+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: x_videos_scraper_dag.x_login_task manual__2025-05-23T09:37:41.892436+00:00 [queued]>
[2025-05-23T09:37:42.429+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: x_videos_scraper_dag.x_login_task manual__2025-05-23T09:37:41.892436+00:00 [queued]>
[2025-05-23T09:37:42.429+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-23T09:37:42.441+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): x_login_task> on 2025-05-23 09:37:41.892436+00:00
[2025-05-23T09:37:42.444+0000] {standard_task_runner.py:72} INFO - Started process 272545 to run task
[2025-05-23T09:37:42.446+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'x_videos_scraper_dag', 'x_login_task', 'manual__2025-05-23T09:37:41.892436+00:00', '--job-id', '6659', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_x.py', '--cfg-path', '/tmp/tmp3qmsaiht']
[2025-05-23T09:37:42.448+0000] {standard_task_runner.py:105} INFO - Job 6659: Subtask x_login_task
[2025-05-23T09:37:42.499+0000] {task_command.py:467} INFO - Running <TaskInstance: x_videos_scraper_dag.x_login_task manual__2025-05-23T09:37:41.892436+00:00 [running]> on host f3ad03241d5f
[2025-05-23T09:37:42.585+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='x_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='x_login_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T09:37:41.892436+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-23T09:37:41.892436+00:00'
[2025-05-23T09:37:42.586+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-23T09:37:42.616+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/pipeline_x.py", line 46, in login_x
    return x_login(X_PASSWORD=X_PASSWORD,
  File "/opt/airflow/dags/tasks/x_login.py", line 4, in x_login
    ti= context["ti"]
KeyError: 'ti'
[2025-05-23T09:37:42.624+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=x_videos_scraper_dag, task_id=x_login_task, run_id=manual__2025-05-23T09:37:41.892436+00:00, execution_date=20250523T093741, start_date=20250523T093742, end_date=20250523T093742
[2025-05-23T09:37:42.632+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-23T09:37:42.632+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6659 for task x_login_task ('ti'; 272545)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/pipeline_x.py", line 46, in login_x
    return x_login(X_PASSWORD=X_PASSWORD,
  File "/opt/airflow/dags/tasks/x_login.py", line 4, in x_login
    ti= context["ti"]
KeyError: 'ti'
[2025-05-23T09:37:42.675+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2025-05-23T09:37:42.690+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-23T09:37:42.694+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
