[2025-05-20T03:44:36.547+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-20T03:44:36.564+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper_task manual__2025-05-20T03:44:34.847173+00:00 [queued]>
[2025-05-20T03:44:36.572+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper_task manual__2025-05-20T03:44:34.847173+00:00 [queued]>
[2025-05-20T03:44:36.572+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-20T03:44:36.586+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): tiktok_videos_scraper_task> on 2025-05-20 03:44:34.847173+00:00
[2025-05-20T03:44:36.589+0000] {standard_task_runner.py:72} INFO - Started process 3564 to run task
[2025-05-20T03:44:36.592+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'tiktok_videos_scraper_dag', 'tiktok_videos_scraper_task', 'manual__2025-05-20T03:44:34.847173+00:00', '--job-id', '6170', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_tiktok.py', '--cfg-path', '/tmp/tmpbu7nm0p5']
[2025-05-20T03:44:36.594+0000] {standard_task_runner.py:105} INFO - Job 6170: Subtask tiktok_videos_scraper_task
[2025-05-20T03:44:36.640+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_videos_scraper_dag.tiktok_videos_scraper_task manual__2025-05-20T03:44:34.847173+00:00 [running]> on host 05534d39966d
[2025-05-20T03:44:36.724+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='tiktok_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='tiktok_videos_scraper_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T03:44:34.847173+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T03:44:34.847173+00:00'
[2025-05-20T03:44:36.726+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-20T03:49:43.719+0000] {local_task_job_runner.py:341} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-20T03:49:43.722+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2025-05-20T03:49:43.723+0000] {process_utils.py:132} INFO - Sending 15 to group 3564. PIDs of all processes in the group: [3567, 3579, 3583, 3584, 3615, 3624, 3675, 3677, 3709, 3751, 3564]
[2025-05-20T03:49:43.724+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 3564
[2025-05-20T03:49:43.724+0000] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-20T03:49:43.738+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3751, status='terminated', started='03:47:39') (3751) terminated with exit code None
[2025-05-20T03:49:43.793+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3583, status='terminated', started='03:44:38') (3583) terminated with exit code None
[2025-05-20T03:49:43.794+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3624, status='terminated', started='03:44:39') (3624) terminated with exit code None
[2025-05-20T03:49:43.794+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3709, status='terminated', started='03:44:39') (3709) terminated with exit code None
[2025-05-20T03:49:43.794+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3579, status='terminated', started='03:44:38') (3579) terminated with exit code None
[2025-05-20T03:49:43.794+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3677, status='terminated', started='03:44:39') (3677) terminated with exit code None
[2025-05-20T03:49:43.794+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3615, status='terminated', started='03:44:39') (3615) terminated with exit code None
[2025-05-20T03:49:43.892+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3584, status='terminated', started='03:44:38') (3584) terminated with exit code None
[2025-05-20T03:49:43.893+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3675, status='terminated', started='03:44:39') (3675) terminated with exit code None
[2025-05-20T03:50:41.230+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=3564, name='airflow task ru', status='sleeping', started='03:44:35') did not respond to SIGTERM. Trying SIGKILL
[2025-05-20T03:50:41.243+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=3567, name='node', status='sleeping', started='03:44:37') did not respond to SIGTERM. Trying SIGKILL
[2025-05-20T03:50:41.243+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 3564
[2025-05-20T03:50:41.258+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3564, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='03:44:35') (3564) terminated with exit code -9
[2025-05-20T03:50:41.259+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3567, name='node', status='terminated', started='03:44:37') (3567) terminated with exit code None
[2025-05-20T03:50:41.260+0000] {standard_task_runner.py:190} ERROR - ('Job 6170 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
