[2025-05-13T02:19:32.888+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-13T02:19:32.899+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-13T02:19:32.203588+00:00 [queued]>
[2025-05-13T02:19:32.903+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-13T02:19:32.203588+00:00 [queued]>
[2025-05-13T02:19:32.904+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-05-13T02:19:32.911+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): ins_videos_scraper> on 2025-05-13 02:19:32.203588+00:00
[2025-05-13T02:19:32.913+0000] {standard_task_runner.py:72} INFO - Started process 105 to run task
[2025-05-13T02:19:32.916+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'instagram_videos_scraper_dag', 'ins_videos_scraper', 'manual__2025-05-13T02:19:32.203588+00:00', '--job-id', '5322', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmplr5o6fmj']
[2025-05-13T02:19:32.918+0000] {standard_task_runner.py:105} INFO - Job 5322: Subtask ins_videos_scraper
[2025-05-13T02:19:32.967+0000] {task_command.py:467} INFO - Running <TaskInstance: instagram_videos_scraper_dag.ins_videos_scraper manual__2025-05-13T02:19:32.203588+00:00 [running]> on host 79b7354865cb
[2025-05-13T02:19:33.027+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='instagram_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='ins_videos_scraper' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T02:19:32.203588+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-13T02:19:32.203588+00:00'
[2025-05-13T02:19:33.028+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-13T02:19:33.030+0000] {logging_mixin.py:190} INFO - Scraping Instagram profile: baukrysie
[2025-05-13T02:19:34.079+0000] {selenium_manager.py:133} WARNING - The chromedriver version (136.0.7103.59) detected in PATH at /usr/bin/chromedriver might not be compatible with the detected chrome version (136.0.7103.92); currently, chromedriver 136.0.7103.92 is recommended for chrome 136.*, so it is advised to delete the driver in PATH and retry
[2025-05-13T02:19:35.516+0000] {logging_mixin.py:190} INFO - url: https://www.instagram.com/baukrysie/
[2025-05-13T02:19:37.905+0000] {logging_mixin.py:190} INFO - Step 1 of 2 - Loading profile page
[2025-05-13T02:19:37.905+0000] {logging_mixin.py:190} INFO - Extracting videos...
[2025-05-13T02:19:40.934+0000] {logging_mixin.py:190} INFO - Count: 1, Limit: 10
[2025-05-13T02:19:40.935+0000] {logging_mixin.py:190} INFO - Scrolling... 1 iterations
[2025-05-13T02:19:41.153+0000] {logging_mixin.py:190} INFO - Found 51 video tags
[2025-05-13T02:19:41.328+0000] {logging_mixin.py:190} INFO - Extracted 0 video URLs
[2025-05-13T02:19:41.329+0000] {logging_mixin.py:190} INFO -  No data found
[2025-05-13T02:19:41.492+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe5efdb580>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3c952b68e56e8a1e1a7e58eabad3861b
[2025-05-13T02:19:41.492+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe5efda170>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3c952b68e56e8a1e1a7e58eabad3861b
[2025-05-13T02:19:41.493+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efe5efd9cc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3c952b68e56e8a1e1a7e58eabad3861b
[2025-05-13T02:19:41.494+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-13T02:19:41.502+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-13T02:19:41.502+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=instagram_videos_scraper_dag, task_id=ins_videos_scraper, run_id=manual__2025-05-13T02:19:32.203588+00:00, execution_date=20250513T021932, start_date=20250513T021932, end_date=20250513T021941
[2025-05-13T02:19:41.550+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-05-13T02:19:41.563+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-13T02:19:41.565+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
