[2025-05-26T08:17:13.463+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-26T08:17:13.474+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.get_links_task manual__2025-05-26T08:17:12.614377+00:00 [queued]>
[2025-05-26T08:17:13.478+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tiktok_videos_scraper_dag.get_links_task manual__2025-05-26T08:17:12.614377+00:00 [queued]>
[2025-05-26T08:17:13.478+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2025-05-26T08:17:13.486+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): get_links_task> on 2025-05-26 08:17:12.614377+00:00
[2025-05-26T08:17:13.489+0000] {standard_task_runner.py:72} INFO - Started process 287 to run task
[2025-05-26T08:17:13.492+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'tiktok_videos_scraper_dag', 'get_links_task', 'manual__2025-05-26T08:17:12.614377+00:00', '--job-id', '6773', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_tiktok.py', '--cfg-path', '/tmp/tmpsnkh_sa1']
[2025-05-26T08:17:13.494+0000] {standard_task_runner.py:105} INFO - Job 6773: Subtask get_links_task
[2025-05-26T08:17:13.534+0000] {task_command.py:467} INFO - Running <TaskInstance: tiktok_videos_scraper_dag.get_links_task manual__2025-05-26T08:17:12.614377+00:00 [running]> on host 6bc766836e0a
[2025-05-26T08:17:13.594+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='tiktok_videos_scraper_dag' AIRFLOW_CTX_TASK_ID='get_links_task' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T08:17:12.614377+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-26T08:17:12.614377+00:00'
[2025-05-26T08:17:13.595+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-26T08:18:36.095+0000] {timeout.py:68} ERROR - Process timed out, PID: 287
[2025-05-26T08:18:49.272+0000] {local_task_job_runner.py:341} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-05-26T08:18:49.273+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2025-05-26T08:18:49.274+0000] {process_utils.py:132} INFO - Sending 15 to group 287. PIDs of all processes in the group: [290, 287]
[2025-05-26T08:18:49.274+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 287
[2025-05-26T08:18:49.274+0000] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-26T08:18:49.277+0000] {unix_events.py:1408} WARNING - Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 290 is closed
[2025-05-26T08:18:49.279+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=290, status='terminated', started='08:17:13') (290) terminated with exit code None
[2025-05-26T08:18:49.288+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-26T08:18:49.307+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=287, status='terminated', exitcode=0, started='08:17:13') (287) terminated with exit code 0
